# https://docs.readthedocs.io/en/stable/tutorial/

version: 2

python:
  version: 3.7
  #
  # Install our python package before building the docs
  #
  install:
    - method: pip

sphinx:
  fail_on_warning: true
